gamemode:
  enabled: true
fly:
  enabled: true
teleport:
  enabled: true
godmode:
  enabled: true
heal:
  enabled: true
vanish:
  enabled: true
spawn:
  enabled: true
  on-join: true
  on-death: true
  on-void: true
trash:
  enabled: true
orbitalcannon:
  enabled: true
  tell-to-victim: true
smite:
  enabled: true
kill:
  enabled: true
warp:
  enabled: true
home:
  enabled: true
speed:
  enabled: true
killmobs:
  enabled: true
  async: true #recomanded: true
spawnmob:
  enabled: true
  async: true #recomanded: true
tpa:
  enabled: true
  expiration: 60 #in seconds

chat:
  enabled: true
  format: "%sender%: %message%"
  blacklist-words:
    - fuck
    - shit
messages: en

world-manipulator:
  enable: true
  rules:
    anti-hunger: true
    anti-weather: true
    anti-join-message: true
    anti-mob-spawn: true


