name: KoreRecoded
version: '${project.version}'
main: me.ghostdevelopment.kore.Kore
load: STARTUP

commands:
  kore:

  # Gamemodes
  gmc:
  gms:
  gma:
  gmsp:
  gamemode:
    aliases:
      - gm
  fly:
  teleport:
    aliases:
      - tp
      - tpto
