name: KoreRecoded
version: '${project.version}'
main: me.ghostdevelopment.kore.Kore
load: STARTUP

commands:
  kore:

  gmc:
  gms:
  gma:
  gmsp:
  gamemode:
    aliases:
      - gm

  fly:

  teleport:
    aliases:
      - tp
      - tpto
  god:
  heal:

permissions:
  kore.*:
    description: ""
  kore.reload:
    description: ""
  kore.teleport:
    description: ""
  kore.tp:
    description: ""
  kore.gamemode:
    description: ""
  kore.gamemode.*:
    description: ""
  kore.gamemode.creative:
    description: ""
  kore.gamemode.survival:
    description: ""
  kore.gamemode.adventure:
    description: ""
  kore.gamemode.spectator:
    description: ""
  kore.godmode:
    description: ""
  kore.heal:
    description: ""