name: Kore
version: 1.11.1
main: me.ghostdevelopment.kore.Kore
load: STARTUP

commands:
    kore:

    gmc:
    gms:
    gma:
    gmsp:
    gamemode:
        aliases:
            - gm

    fly:

    teleport:
        aliases:
            - tp
            - tpto
    god:
    heal:
    vanish:
        aliases:
            - v
    setspawn:
    spawn:
    trash:
        aliases:
            - disposal
    orbitalcannon:
    smite:
    kill:
    warp:
    home:
    speed:
    killmobs:
    spawnmob:

permissions:
    kore.*:
        description: ""
    kore.reload:
        description: ""
    kore.teleport:
        description: ""
    kore.tp:
        description: ""
    kore.gamemode:
        description: ""
    kore.gamemode.*:
        description: ""
    kore.gamemode.creative:
        description: ""
    kore.gamemode.survival:
        description: ""
    kore.gamemode.adventure:
        description: ""
    kore.gamemode.spectator:
        description: ""
    kore.godmode:
        description: ""
    kore.heal:
        description: ""
    kore.vanish:
        description: ""
    kore.setspawn:
        description: ""
    kore.spawn:
        description: ""
    kore.trash:
        description: ""
    kore.chatbypass:
        description: ""
    kore.orbitalcannon:
        description: ""
    kore.smite:
        description: ""
    kore.kill:
        description: ""
    kore.warp:
        description: ""
    kore.warp.admin:
        description: ""
    kore.home:
        description: ""
    kore.speed:
        description: ""
    kore.weather:
        description: ""
    kore.chatcolor:
        description: ""
    kore.killmobs:
        description: ""
    kore.spawnmob:
        description: ""
